name: Python application

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
      - run: python actions/til_notice.py
        env: # Or as an environment variable
          TIL_WEBHOOK_URL: ${{ secrets.TIL_WEBHOOK_URL }}
